server:
  port: 8087
spring:
  application:
    name: wire-transfer-service
  config:
    import:
      - optional:configserver:https://ms-config.azurewebsites.net
eureka:
  client:
    service-url:
      defaultZone: https://ms-discovery.azurewebsites.net/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-wireTransfer: /api/v1/wiretransfer
  path-customerProductDomain: https://ms-customerproduct.azurewebsites.net
  path-get: /api/v1/customerPassivesProducts/
  path-update: /api/v1/customerPassivesProducts/update/
  path-operationDomain: https://ms-operation.azurewebsites.net
  path-post: /api/v1/customerPassivesProducts